# Generated by Django 5.2.17 on 2026-09-21 09:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_number', models.PositiveIntegerField(editable=False, unique=True, verbose_name='شماره پرونده')),
                ('first_name', models.CharField(max_length=60, verbose_name='نام')),
                ('last_name', models.CharField(max_length=80, verbose_name='نام خانوادگی')),
                ('national_id', models.CharField(max_length=10, unique=True, verbose_name='کدملی')),
                ('mobile', models.CharField(max_length=11, verbose_name='موبایل')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('file_location', models.CharField(blank=True, help_text='مثلاً: قفسه ۳، ردیف ۲', max_length=100, verbose_name='محل نگهداری پرونده')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('search_name', models.CharField(db_index=True, default='', editable=False, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
            ],
            options={
                'verbose_name': 'بیمار',
                'verbose_name_plural': 'بیماران',
                'ordering': ['-file_number'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='نام کاربری')),
                ('action', models.CharField(choices=[('login', 'ورود به برنامه'), ('patient_created', 'ثبت بیمار جدید'), ('patient_updated', 'ویرایش پرونده'), ('patient_deleted', 'حذف بیمار'), ('visit_added', 'ثبت مراجعه'), ('visit_updated', 'ویرایش مراجعه'), ('visit_deleted', 'حذف مراجعه')], max_length=20, verbose_name='عملیات')),
                ('patient_label', models.CharField(blank=True, max_length=200, verbose_name='بیمار')),
                ('details', models.TextField(blank=True, verbose_name='جزئیات')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='patients.patient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'لاگ تغییرات',
                'verbose_name_plural': 'لاگ تغییرات',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='تاریخ مراجعه')),
                ('notes', models.CharField(blank=True, max_length=300, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient', verbose_name='بیمار')),
            ],
            options={
                'verbose_name': 'مراجعه',
                'verbose_name_plural': 'مراجعه\u200cها',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
