# Generated by Django 5.2.17 on 2026-09-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='کدملی'),
        ),
    ]
