# Generated by Django 5.2.17 on 2026-09-24 10:19

import django.db.models.deletion
import patients.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_national_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مبلغ (تومان)'),
        ),
        migrations.CreateModel(
            name='PatientPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=patients.models.patient_photo_path, verbose_name='عکس')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='توضیح')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='patients.patient', verbose_name='بیمار')),
                ('uploaded_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='بارگذاری\u200cکننده')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='patients.visit', verbose_name='مراجعه')),
            ],
            options={
                'verbose_name': 'عکس',
                'verbose_name_plural': 'عکس\u200cها',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
