# Generated by Django 5.2.17 on 2026-09-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_visit_amount_patientphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='father_name',
            field=models.CharField(blank=True, max_length=60, verbose_name='نام پدر'),
        ),
        migrations.AddField(
            model_name='patient',
            name='hospitalization_history',
            field=models.CharField(blank=True, max_length=200, verbose_name='سابقه بستری در بیمارستان'),
        ),
        migrations.AddField(
            model_name='patient',
            name='hospitalization_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='علت بستری'),
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_conditions',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='بیماری\u200cهای خاص'),
        ),
        migrations.AddField(
            model_name='patient',
            name='other_conditions',
            field=models.CharField(blank=True, max_length=300, verbose_name='سایر بیماری\u200cها'),
        ),
        migrations.AddField(
            model_name='patient',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='patient_avatars/%Y/%m/', verbose_name='عکس بیمار'),
        ),
    ]
